# Generated by Django 4.0.4 on 2022-04-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Заголовок'),
        ),
    ]
